import type { Metadata } from "next";
import Link from "next/link";
import type { ReactNode } from "react";
import { JsonLd } from "~/components/seo/json-ld";
import { breadcrumbStructuredData } from "~/lib/structured-data";
import { pageMetadata } from "~/lib/site-metadata";
import {
  LegalContent,
  LegalControllerCard,
  LegalExternalLink as ExternalLink,
  LegalList,
  LegalMail as Mail,
  LegalPageHero,
  LegalSection,
  LegalSubheading,
  LegalTable,
  legalLinkClass,
  legalStrongClass,
} from "~/components/legal/legal-layout";
import { TERMS_UPDATED_AT, legalEntity } from "~/lib/legal";
import { subscriptionPlans } from "~/lib/pricing";
import { repositoryUrl } from "~/lib/site-config";

export const metadata: Metadata = pageMetadata({
  title: "Terms and Conditions",
  description:
    "The terms that govern your use of Melodyc, including credits, subscriptions, AI-generated music, and your rights as a user.",
  path: "/terms",
});

function Strong({ children }: { children: ReactNode }) {
  return <strong className={legalStrongClass}>{children}</strong>;
}

export default function TermsPage() {
  return (
    <div className="min-w-0 overflow-x-hidden">
      <JsonLd
        data={breadcrumbStructuredData("Terms and Conditions", "/terms")}
      />
      <LegalPageHero title="Terms and Conditions" updatedAt={TERMS_UPDATED_AT} />

      <LegalContent>
        <LegalControllerCard index={1} title="Service Provider" />

        <LegalSection title="1. Introduction and Definitions" index={2}>
          <p>
            These Terms and Conditions (&quot;Terms&quot;) govern your access
            to and use of <Strong>Melodyc</Strong>, the AI music generation
            platform available at <Strong>{legalEntity.website}</Strong>,
            including the free public demo (the &quot;Service&quot;), operated
            by <Strong>{legalEntity.name}</Strong> (&quot;we&quot;,
            &quot;us&quot;, or &quot;our&quot;).
          </p>
          <p>
            By creating an account or using the Service, you confirm that you
            have read, understood, and accepted these Terms. If you do not
            agree, you may not use the Service.
          </p>
          <p>
            These Terms are drafted in accordance with Articles 1341 and 1342
            of the Italian Civil Code, Legislative Decree 206/2005 (Italian
            Consumer Code), Legislative Decree 70/2003 on electronic commerce,
            Regulation (EU) 2016/679 (GDPR), Regulation (EU) 2024/1689 (AI
            Act), and all other applicable Italian and EU laws.
          </p>

          <LegalSubheading>Definitions</LegalSubheading>
          <LegalList>
            <li>
              <Strong>&quot;User&quot;</Strong>: any natural or legal person
              who uses the Service, with or without an account.
            </li>
            <li>
              <Strong>&quot;Consumer&quot;</Strong>: a User who is a natural
              person acting for purposes outside their trade, business, craft,
              or profession.
            </li>
            <li>
              <Strong>&quot;Credits&quot;</Strong>: units that allow the User
              to generate songs. One credit is used for each song generated
              successfully.
            </li>
            <li>
              <Strong>&quot;Input&quot;</Strong>: the descriptions, prompts,
              lyrics, style tags, titles, and settings submitted by the User.
            </li>
            <li>
              <Strong>&quot;Output&quot;</Strong>: the songs, lyrics, style
              tags, categories, and cover images generated by the Service from
              the Input.
            </li>
            <li>
              <Strong>&quot;Published Content&quot;</Strong>: Output that the
              User chooses to make visible to other users in Discover.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="2. Description of the Service" index={3}>
          <p>Melodyc is an AI-powered platform that allows you to:</p>
          <LegalList>
            <li>
              Generate original songs from a text description, from your own
              lyrics, or from lyrics written by the AI.
            </li>
            <li>
              Create vocal or instrumental tracks and guide the result with
              styles, genres, and generation settings.
            </li>
            <li>
              Store your songs in a personal library, play them, and download
              them in WAV, MP3, or FLAC together with their cover image.
            </li>
            <li>
              Publish your songs to Discover, explore music created by the
              community, and like the songs you enjoy.
            </li>
            <li>
              Create a public profile with a username and a profile picture,
              follow other creators, and be followed by them.
            </li>
            <li>
              Try a limited free demo without creating an account.
            </li>
          </LegalList>
          <p className="mt-3">
            <Strong>AI transparency:</Strong> all music, lyrics, and images
            produced by the Service are generated by artificial intelligence
            systems. Results are probabilistic, may vary for the same Input,
            and may not always match your expectations.
          </p>
        </LegalSection>

        <LegalSection title="3. Registration and Account" index={4}>
          <LegalList>
            <li>
              Registration is free and requires a name, a valid email address,
              and a password. You must verify your email address before you
              can sign in.
            </li>
            <li>
              You may choose a public username and upload a profile picture.
              You must own or have the right to use the image, and both must
              comply with Section 6.
            </li>
            <li>
              You must be at least <Strong>16 years of age</Strong> to use the
              Service. Purchases are reserved to Users who are of legal age
              under the law of their country, or who have the authorization of
              a parent or legal guardian.
            </li>
            <li>
              Upon registration you receive <Strong>20 free credits</Strong>,
              with no payment information required.
            </li>
            <li>
              You are responsible for keeping your login credentials
              confidential and for all activity carried out through your
              account. Notify us immediately of any unauthorized use.
            </li>
            <li>
              You agree to provide truthful, accurate, and up-to-date
              information, and to hold only one personal account.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="4. Credits, Plans, and Payments" index={5}>
          <LegalSubheading>4.1 Credit System</LegalSubheading>
          <LegalList>
            <li>
              <Strong>One credit = one song generated successfully.</Strong> If
              a generation fails, no credit is deducted.
            </li>
            <li>
              Credits have no monetary value, cannot be converted into cash,
              and cannot be transferred to other accounts.
            </li>
            <li>
              Unused credits roll over from one billing period to the next and
              remain available as long as your account is active.
            </li>
          </LegalList>

          <LegalSubheading>4.2 Available Plans</LegalSubheading>
          <LegalTable
            headers={["Plan", "Price", "Credits per month"]}
            rows={subscriptionPlans.map((plan) => [
              plan.name,
              `${plan.price} / month`,
              String(plan.credits),
            ])}
          />
          <p>
            Plans are monthly subscriptions that renew automatically until
            cancelled. Credits are added after the first successful payment
            and after each successful renewal. The prices and conditions in
            force are always those shown on the{" "}
            <Link href="/#pricing" className={legalLinkClass}>
              pricing page
            </Link>{" "}
            and at checkout at the time of purchase.
          </p>

          <LegalSubheading>4.3 Payments and Billing</LegalSubheading>
          <LegalList>
            <li>
              Purchases are processed by <Strong>Polar</Strong>, which acts as
              Merchant of Record: Polar sells the subscription to you, collects
              the payment, calculates and remits applicable taxes (such as VAT)
              based on your country, and issues the related invoice or
              receipt. Polar&apos;s{" "}
              <ExternalLink href="https://polar.sh/legal/terms">
                terms
              </ExternalLink>{" "}
              also apply to the purchase.
            </li>
            <li>
              Any taxes due are shown at checkout before you confirm the
              payment. We never receive or store your card details.
            </li>
            <li>
              You can review your payments and{" "}
              <Strong>cancel your subscription at any time</Strong> from the
              Billing page, through the Polar customer portal. Cancellation
              stops future renewals; credits already added remain available.
            </li>
            <li>
              If a renewal payment fails, no new credits are added until the
              payment is completed.
            </li>
          </LegalList>

          <LegalSubheading>4.4 Right of Withdrawal and Refunds</LegalSubheading>
          <p>
            If you are a Consumer, you have the right to withdraw from each
            purchase within <Strong>14 days</Strong> of the payment, without
            giving any reason and without penalty (Articles 52 to 59 of the
            Italian Consumer Code).
          </p>
          <LegalList>
            <li>
              At checkout you request that the Service start immediately, so
              that the purchased credits are available right away.
            </li>
            <li>
              If you withdraw and{" "}
              <Strong>have not used any credit</Strong> from that purchase, you
              receive a full refund.
            </li>
            <li>
              If you have already used part of those credits, you receive a
              refund proportional to the unused credits, because the Service
              has been partially performed at your request (Art. 57(3) of the
              Italian Consumer Code).
            </li>
            <li>
              The right of withdrawal does not apply once all the credits of
              that purchase have been used, because the Service has been fully
              performed with your prior express consent and acknowledgment
              (Art. 59(1)(a) of the Italian Consumer Code).
            </li>
            <li>
              To withdraw, send an unequivocal statement to{" "}
              <Mail address={legalEntity.email} /> or by PEC to{" "}
              <Mail address={legalEntity.pec} />, indicating your account email
              and the purchase concerned. You may also use the model
              withdrawal form in Annex I(B) of the Consumer Code, but it is not
              mandatory.
            </li>
            <li>
              Refunds are issued through Polar within{" "}
              <Strong>14 days</Strong> of receiving your request, using the
              same payment method used for the purchase, at no cost to you.
              The related credits are removed from your account.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="5. Your Content and AI-Generated Music" index={6}>
          <LegalSubheading>5.1 Input</LegalSubheading>
          <LegalList>
            <li>
              You retain all rights you hold in your Input, including lyrics
              you write yourself.
            </li>
            <li>
              You grant us a limited, non-exclusive, royalty-free license to
              use your Input solely to generate the Output and provide the
              Service to you.
            </li>
            <li>
              We do <Strong>not</Strong> use your Input or Output to train AI
              models.
            </li>
          </LegalList>

          <LegalSubheading>5.2 Output</LegalSubheading>
          <LegalList>
            <li>
              As between you and us, <Strong>we claim no ownership</Strong> of
              the Output generated from your Input, and to the extent we hold
              any rights in it, we assign them to you. You may use the Output
              for any lawful purpose, including commercial purposes, subject
              to these Terms.
            </li>
            <li>
              Under Italian and EU law, copyright protects works that are the
              result of human intellectual creativity. Output generated
              entirely by AI may therefore not be protected by copyright, and
              we cannot guarantee that it can be registered or enforced
              against third parties.
            </li>
            <li>
              Because of the nature of AI, similar or identical Output may be
              generated for other users. We do not guarantee that the Output is
              unique or exclusive.
            </li>
            <li>
              You are solely responsible for how you use and distribute the
              Output, including compliance with the rules of streaming
              platforms, distributors, and collecting societies on
              AI-generated content.
            </li>
          </LegalList>

          <LegalSubheading>5.3 Published Content</LegalSubheading>
          <LegalList>
            <li>
              When you publish a song, you grant us and the other users of the
              Service a non-exclusive, worldwide, royalty-free license to host,
              stream, display, and make it searchable within the Service, for
              as long as it remains published.
            </li>
            <li>
              Published songs show your name, username, and profile picture,
              and appear on your public profile page. You can unpublish a song
              at any time; it will then no longer be visible to other users.
            </li>
            <li>
              We may remove Published Content, profile pictures, or usernames
              that violate these Terms or the law, or that are reported to us
              as infringing third-party rights.
            </li>
          </LegalList>

          <LegalSubheading>5.4 Melodyc Platform and Open Source</LegalSubheading>
          <LegalList>
            <li>
              The Melodyc source code is published under the{" "}
              <ExternalLink href={`${repositoryUrl}/blob/main/LICENSE.MD`}>
                MIT License
              </ExternalLink>
              , which governs your use of the code. These Terms govern the use
              of the hosted Service at {legalEntity.website}.
            </li>
            <li>
              The MIT License does not grant any right to the Melodyc name,
              logo, and other distinctive signs, which remain the exclusive
              property of {legalEntity.name} and are protected under Italian
              and international law (Legislative Decree 30/2005). Self-hosted
              versions must not be presented as the official Melodyc service.
            </li>
            <li>
              The AI models used by the Service are provided by third parties
              under their own licenses.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="6. Acceptable Use" index={7}>
          <p>By using the Service, you agree not to:</p>
          <LegalList>
            <li>
              Submit lyrics or other Input that you do not own or are not
              authorized to use, or that infringe copyrights, trademarks, or
              other third-party rights.
            </li>
            <li>
              Generate or publish content that is illegal, defamatory, obscene,
              violent, discriminatory, that incites hatred, or that violates
              human dignity or the rights of minors.
            </li>
            <li>
              Use the Service to imitate the voice, name, or identity of real
              artists or people, or to create deepfakes or misleading content,
              in violation of the AI Act or other applicable law.
            </li>
            <li>
              Present AI-generated Output as created entirely by a human where
              disclosure is required by law, or remove any marking that
              identifies the Output as AI-generated.
            </li>
            <li>
              Use a username or profile picture that impersonates another
              person or brand, infringes third-party rights, or is offensive,
              obscene, or misleading.
            </li>
            <li>
              Resell, sublicense, or share access to your account or credits
              with third parties.
            </li>
            <li>
              Create multiple accounts or use automated means to abuse free
              credits or the free demo.
            </li>
            <li>
              Access or attempt to access other users&apos; accounts or
              private songs, or interfere with the security of the Service.
            </li>
            <li>
              Overload the Service with excessive or automated requests,
              including scraping and denial-of-service attacks.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="7. Service Availability" index={8}>
          <LegalList>
            <li>
              We strive to keep the Service available, but we do not guarantee
              uninterrupted or error-free operation.
            </li>
            <li>
              The Service may be temporarily suspended for maintenance,
              updates, or reasons beyond our control.
            </li>
            <li>
              Generation times depend on system load and on the settings you
              choose. Songs are processed in a queue.
            </li>
            <li>
              The free demo is limited to one short generation per visitor per
              day and may be changed or discontinued at any time.
            </li>
            <li>
              We may modify, update, or remove features of the Service. If a
              change significantly reduces the features of a paid plan, we
              will inform you in advance and you may cancel your subscription.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="8. Limitation of Liability" index={9}>
          <p>
            To the maximum extent permitted by law (Articles 1218 and 1229 of
            the Italian Civil Code):
          </p>
          <LegalList>
            <li>
              We are not liable for indirect or consequential damages, such as
              loss of profit, loss of opportunity, or business interruption.
            </li>
            <li>
              Our total liability towards business Users for any claim relating
              to the Service shall not exceed the amount paid by the User in
              the <Strong>12 months</Strong> preceding the event that gave rise
              to the claim.
            </li>
            <li>
              We recommend downloading and keeping a copy of the songs that
              matter to you. We are not liable for the loss of Output caused by
              events beyond our reasonable control.
            </li>
            <li>
              We are not liable for malfunctions or interruptions of
              third-party services (such as Polar, AWS, or Modal) that are
              beyond our reasonable control.
            </li>
            <li>
              Nothing in these Terms excludes or limits our liability for
              willful misconduct or gross negligence (Art. 1229 of the Italian
              Civil Code), for death or personal injury, or the rights granted
              to Consumers by mandatory law, including the Italian Consumer
              Code.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="9. Warranties" index={10}>
          <p>
            The Service is provided &quot;as is&quot; and &quot;as
            available&quot;. Without prejudice to the legal guarantee of
            conformity for digital content and services granted to Consumers
            (Articles 135-octies et seq. of the Italian Consumer Code), we do
            not guarantee that the Output will meet your expectations, match a
            specific style or quality, or be suitable for a particular purpose.
          </p>
        </LegalSection>

        <LegalSection title="10. Suspension and Termination" index={11}>
          <LegalSubheading>10.1 By the User</LegalSubheading>
          <LegalList>
            <li>
              You may stop using the Service and delete your account at any
              time from Account &gt; Security, or by writing to{" "}
              <Mail address={legalEntity.email} />.
            </li>
            <li>
              Deleting your account permanently removes your songs, cover
              images, and any remaining credits, and cancels any active
              subscription. Before deleting, you can download your songs and
              request a copy of your data (Art. 20 GDPR).
            </li>
            <li>
              Remember to cancel any active subscription to stop future
              renewals.
            </li>
          </LegalList>

          <LegalSubheading>10.2 By Us</LegalSubheading>
          <LegalList>
            <li>
              We may suspend or close your account if you violate these Terms,
              after notifying you in writing with the reasons and, where
              possible, giving you the opportunity to remedy.
            </li>
            <li>
              In case of serious violations (illegal activity, fraud, abuse of
              the systems, or infringement of third-party rights), suspension
              may be immediate.
            </li>
            <li>
              If we close your account without any violation on your part, we
              will refund the unused credits purchased in the previous 12
              months.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="11. Indemnification" index={12}>
          <p>
            If you use the Service for business purposes, you agree to
            indemnify and hold harmless {legalEntity.name}, its directors,
            employees, and collaborators from claims, damages, and expenses
            (including reasonable legal fees) arising from your violation of
            these Terms, from Input or Published Content that infringes
            third-party rights, or from your use of the Service in violation
            of the law. For Consumers, the general rules of liability under
            Italian law apply.
          </p>
        </LegalSection>

        <LegalSection title="12. Data Protection" index={13}>
          <p>
            The processing of personal data is described in our{" "}
            <Link href="/privacy" className={legalLinkClass}>
              Privacy Policy
            </Link>{" "}
            and{" "}
            <Link href="/cookies" className={legalLinkClass}>
              Cookie Policy
            </Link>
            , which we invite you to read carefully.
          </p>
        </LegalSection>

        <LegalSection title="13. Changes to These Terms" index={14}>
          <LegalList>
            <li>
              We may update these Terms to reflect changes to the Service, the
              law, or our business. The updated version is published on this
              page with a new &quot;Last updated&quot; date.
            </li>
            <li>
              In case of material changes, we will inform you through the
              Service or by email at least <Strong>15 days</Strong> before they
              take effect.
            </li>
            <li>
              If you do not accept the changes, you may cancel your
              subscription and close your account before they take effect.
              Continuing to use the Service after that date means you accept
              the updated Terms.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="14. General Provisions" index={15}>
          <LegalList>
            <li>
              <Strong>Entire agreement:</Strong> these Terms, together with the
              Privacy Policy and the Cookie Policy, constitute the entire
              agreement between you and {legalEntity.name} regarding the
              Service.
            </li>
            <li>
              <Strong>Assignment:</Strong> you may not assign your rights or
              obligations under these Terms without our prior written consent.
              We may assign these Terms to a company of our group or to a third
              party in case of merger, acquisition, or transfer of the
              business, provided that your rights are not reduced.
            </li>
            <li>
              <Strong>Severability:</Strong> if a provision is found invalid or
              unenforceable, it will be replaced by the applicable legal
              provision, and the remaining provisions remain in force.
            </li>
            <li>
              <Strong>No waiver:</Strong> failure to enforce a right or
              provision does not constitute a waiver of it.
            </li>
            <li>
              <Strong>Force majeure:</Strong> we are not liable for failures or
              delays caused by events beyond our reasonable control, such as
              natural disasters, infrastructure failures, cyberattacks, or
              orders of public authorities.
            </li>
            <li>
              <Strong>Language:</Strong> these Terms are provided in English. If
              they are translated, the English version prevails, except where
              mandatory law requires otherwise.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection title="15. Governing Law and Disputes" index={16}>
          <LegalList>
            <li>
              These Terms are governed by <Strong>Italian law</Strong>. If you
              are a Consumer residing in another EU country, you also keep the
              protection granted by the mandatory provisions of the law of
              your country of residence (Art. 6 of Regulation (EC) 593/2008).
            </li>
            <li>
              For disputes with <Strong>Consumers</Strong>, the competent court
              is the court of the place where the Consumer resides or is
              domiciled (Art. 66-bis of the Italian Consumer Code).
            </li>
            <li>
              For disputes with <Strong>business Users</Strong>, the{" "}
              <Strong>Court of {legalEntity.court}</Strong> has exclusive
              jurisdiction.
            </li>
            <li>
              Before going to court, we invite you to contact us at{" "}
              <Mail address={legalEntity.email} /> to find an amicable
              solution. Consumers may also turn to an alternative dispute
              resolution (ADR) body under Articles 141 et seq. of the Italian
              Consumer Code.
            </li>
          </LegalList>
        </LegalSection>

        <LegalSection
          title="16. Specific Approval of Clauses (Arts. 1341 and 1342 Italian Civil Code)"
          index={17}
        >
          <p>
            Pursuant to Articles 1341 and 1342 of the Italian Civil Code, the
            User declares to have read and to specifically approve the
            following clauses:
          </p>
          <LegalList>
            <li>Art. 4.4: right of withdrawal and partial refunds</li>
            <li>Art. 5.3: license on Published Content and its removal</li>
            <li>Art. 7: service availability and changes to features</li>
            <li>Art. 8: limitation of liability</li>
            <li>Art. 9: warranties</li>
            <li>Art. 10.2: suspension and termination by us</li>
            <li>Art. 11: indemnification</li>
            <li>Art. 13: changes to these Terms</li>
            <li>Art. 15: jurisdiction for business Users</li>
          </LegalList>
        </LegalSection>

        <LegalSection title="17. Contact Us" index={18}>
          <p>For any questions about these Terms, contact us:</p>
          <ul className="mt-3 space-y-2">
            <li>
              Email: <Mail address={legalEntity.email} />
            </li>
            <li>
              PEC: <Mail address={legalEntity.pec} />
            </li>
            <li>
              Address: {legalEntity.address}, {legalEntity.city}
            </li>
          </ul>
        </LegalSection>
      </LegalContent>
    </div>
  );
}
